# Generated by Django 4.1.5 on 2023-07-05 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bingosync', '0036_alter_game_game_type_value_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='tournament_mode',
            field=models.BooleanField(default=False, verbose_name='TournamentMode'),
        ),
    ]
