# Generated by Django 4.1.5 on 2023-07-17 18:26

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('bingosync', '0036_alter_game_game_type_value_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='is_referee',
            field=models.BooleanField(default=False, verbose_name='Is Referee'),
        ),
        migrations.AddField(
            model_name='room',
            name='tournament_mode',
            field=models.BooleanField(default=False, verbose_name='TournamentMode'),
        ),
        migrations.CreateModel(
            name='KickPlayersEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Sent')),
                ('player_color_value', models.IntegerField(choices=[(2, 'Red'), (3, 'Blue'), (4, 'Green'), (5, 'Orange'), (6, 'Purple'), (7, 'Navy'), (8, 'Teal'), (9, 'Pink'), (10, 'Forest'), (11, 'Yellow')])),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bingosync.player')),
            ],
            options={
                'get_latest_by': 'timestamp',
                'abstract': False,
            },
        ),
    ]
