# Generated by Django 4.2.3 on 2023-10-26 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bingosync', '0037_game_fog_of_war_alter_chatevent_player_color_value_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='newcardevent',
            name='fog_of_war',
            field=models.BooleanField(default=False),
        ),
    ]
