# Generated by Django 4.1.5 on 2023-07-05 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bingosync', '0037_room_tournament_mode'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='is_referee',
            field=models.BooleanField(default=False, verbose_name='Is Referee'),
        ),
    ]
