# Generated by Django 4.1.5 on 2023-07-17 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bingosync', '0038_alter_color_values'),
    ]

    operations = [
        migrations.AddField(
            model_name='kickplayersevent',
            name='player_name',
            field=models.CharField(default='Unknown Player', max_length=50),
            preserve_default=False,
        ),
    ]
