# Generated by Django 4.1.5 on 2023-10-26 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bingosync', '0038_newcardevent_fog_of_war'),
    ]

    operations = [
        migrations.AddField(
            model_name='square',
            name='tier',
            field=models.IntegerField(default=0),
        ),
    ]
