# Generated by Django 4.1.5 on 2023-07-17 20:21

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('bingosync', '0039_kickplayersevent_player_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kickplayersevent',
            name='player_name',
        ),
        migrations.AddField(
            model_name='kickplayersevent',
            name='player_uuid',
            field=models.UUIDField(default=uuid.uuid4),
        ),
    ]
